### ISSUE TITLE
[flagd] follow-up refactoring

### ISSUE THREAD

**Issue by thisthat** [open-feature/java-sdk-contrib#390]
```[tasklist]
### Tasks
- [x] Improve retry-logic for gRPC stream ([ctx](https://github.com/open-feature/java-sdk-contrib/pull/378#discussion_r1279580804))
- [x] Abstract gPRC into a generic service ([ctx](https://github.com/open-feature/java-sdk-contrib/pull/378#discussion_r1281078271))
- [x] Improve `initialize(EvaluationContext)` strategy ([ctx](https://github.com/open-feature/java-sdk-contrib/pull/378#discussion_r1281102577))
- [ ] Keep the latest known cache status in case of error ([ctx](https://github.com/open-feature/java-sdk-contrib/pull/378/files#r1282810265))
- [x] Use always OTel interceptor ([ctx](https://github.com/open-feature/java-sdk-contrib/pull/378#discussion_r1280580832))
```

**Comment by toddbaert** [comment]
See my comment [here](https://github.com/open-feature/java-sdk-contrib/pull/378#discussion_r1283687965), I'm not sure we can really do much about the 4th point.

The rest looks good.

**Comment by Kavindu-Dodan** [comment]
I will work on this :)

**Comment by Kavindu-Dodan** [comment]
@thisthat except for [this](https://github.com/open-feature/java-sdk-contrib/pull/378/files#r1282810265), we have completed all other tasks. And this last one is not necessary for the current operation of flagd. Further, in-process provider proposed through https://github.com/open-feature/java-sdk-contrib/issues/411 will provider more options to use flagd. 

I am voting to close this as complete

**Comment by thisthat** [comment]
I think also the last point (always use OTel) is not yet done. 
In the code ([link](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/grpc/strategy/ResolveFactory.java#L15C21-L15C37)), we instrument the gRPC streams only if we pass an SDK instance instead of acting as a library and get the default tracer all the time. OTel docs: https://opentelemetry.io/docs/concepts/instrumentation/libraries/

**Comment by thiyagu06** [comment]
> I think also the last point (always use OTel) is not yet done. In the code ([link](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/grpc/strategy/ResolveFactory.java#L15C21-L15C37)), we instrument the gRPC streams only if we pass an SDK instance instead of acting as a library and get the default tracer all the time. OTel docs: https://opentelemetry.io/docs/concepts/instrumentation/libraries/

We already discussed about this in https://github.com/open-feature/java-sdk-contrib/pull/286#issuecomment-1521935162. are we changing from this stance and planning to use `GlobalOpenTelemetry` ?

**Comment by Kavindu-Dodan** [comment]
@thisthat could you please explain your suggestion in detail? I cannot fully understand the requirements you are proposing.

Besides @thiyagu06 has a good point about using global telemetry.

**Comment by thisthat** [comment]
Sorry to overlook this ticket for so long @thiyagu06 and @Kavindu-Dodan 🤦 
The problem is with the following lines: https://github.com/open-feature/java-sdk-contrib/blob/2f2ce590b3589331f9b4c99bd7a18cf53c7436d8/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/grpc/strategy/ResolveFactory.java#L15-L18

If we don't pass an OTel instance, gRPC will never be instrumented. This is a problem when you work with Agent auto-instrumentation that provides an SDK implementation at runtime.

Since auto-instrumentation for Java is quite powerful (see OTel java-instrumentation or other Observability vendors), I would suggest changing the lines before. If the App developer didn't provide an `OpenTelemetry` instance, we default to using the`GlobalOpenTelemetry` one. This way, also with auto-instrumentation we can attach to the gRPC spans the FF evaluation details.

**Comment by Kavindu-Dodan** [comment]
I checked the concerned usage and I have the following suggestion,

- We should still allow traces-free simple resolving 
- Give an option to use global OTel 
- Continue to support OTel SDK injection through builder 

This fulfils all the requirements.

**Comment by Kavindu-Dodan** [comment]
@thisthat please check this PR with the fix - https://github.com/open-feature/java-sdk-contrib/pull/505

This is the best approach I could think of

**Comment by thisthat** [comment]
> We should still allow traces-free simple resolving

Wouldn't this be achieved through the no-op implementation of the Otel API? 🤔

**Comment by Kavindu-Dodan** [comment]
> > We should still allow traces-free simple resolving
> 
> Wouldn't this be achieved through the no-op implementation of the Otel API? 🤔

We could, but that means we have a few extra calls backed by no-op implementation. And if someone wants to avoid those calls, traces-free resolving helps.
