### ISSUE TITLE
[flagd] Intial version of in-process provider

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/java-sdk-contrib#411]
As mentioned in flagd documentation of  **Creating an in-process flagd provider** [^1], in-process provider comes with unique advantages. This issue focuses on creating the first version of flagd in-process provider in Java.

**Requirements**

- Fulfill requirements outlined by flagd in-process guideline [^1]
- Minimal external dependencies 
- Updated/New ReadMe & usage guide
- Unit & Integration tests 

**Technical requirements**

- Use the same repository directory structure (`providers/flagd`)
- Build both remote and in-process providers into a single dependency (To be decided after the POC)
- Reuse existing interfaces and implementations where possible 

**Tasks** 

- [x] POC implementation and build to detect packaging requirements (no evaluations needed)
- [x] In-process provider with gRPC flag sync capability on basic flags
- [x] Support for JsonLogic evaluators (complex flagd flag configurations)
- [x] Support for flagd custom JsonLogic evaluators 

[^1]: https://github.com/open-feature/flagd/blob/main/docs/other_resources/in-process-providers/specification.md
